
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth-provider"
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Daasing",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies:()=>cookieStore });
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
        {/* <AuthProvider accessToken={session?.access_token}>{children}</AuthProvider> */}
      </body>
    </html>
  );
}



